<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>demo_map_server</RootNamespace>
    <!-- Specifically for semver https://github.com/dotnet/sdk/issues/23839 -->
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Test.Hl7.Fhir.MappingLanguage\CrossVersionResolver.cs" Link="CrossVersionResolver.cs" />
    <Compile Include="..\Test.Hl7.Fhir.MappingLanguage\TestWorkerContext.cs" Link="TestWorkerContext.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="brianpos.Fhir.R4B.DemoFileSystemFhirServer" Version="5.13.4-rc1" />
    <PackageReference Include="brianpos.Fhir.R4B.WebApi.AspNetCore" Version="5.13.4-rc1" />
    <PackageReference Include="Hl7.Fhir.Specification.R4B" Version="5.13.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hl7.Fhir.MappingLanguage\Hl7.Fhir.MappingLanguage.R4B.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hl7.Fhir.Specification.Data.R4" Version="5.13.4" GeneratePathProperty="true" ExcludeAssets="all" />
    <PackageReference Include="Hl7.Fhir.Specification.Data.R4B" Version="5.13.4" GeneratePathProperty="true" ExcludeAssets="all" />
    <PackageReference Include="Hl7.Fhir.Specification.Data.R5" Version="5.13.4" GeneratePathProperty="true" ExcludeAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <!-- https://blog.dangl.me/archive/accessing-nuget-package-paths-in-your-net-sdk-based-csproj-files/ -->
    <Content Include="$(PkgHl7_Fhir_Specification_Data_R4)\contentFiles\any\any\specification.zip">
      <Link>specification.r4.zip</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="$(PkgHl7_Fhir_Specification_Data_R4B)\contentFiles\any\any\specification.zip">
      <Link>specification.zip</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="$(PkgHl7_Fhir_Specification_Data_R5)\contentFiles\any\any\specification.zip">
      <Link>specification.r5.zip</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
