<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <LangVersion>10.0</LangVersion>

    <AssemblyName>Hl7.Fhir.R5.MappingLanguage</AssemblyName>
    <PackageId>brianpos.Fhir.R5.MappingLanguage</PackageId>
    <Version>5.12.1-beta1</Version>
    <Title>HL7 Fhir Mapping Language Engine R5</Title>
    <Summary>HL7 Fhir R5 Mapping Language Engine ported from the Java code</Summary>
    <Description>Includes a serializer, parser and execution engine</Description>
    <PackageTags>HL7;FHIR;FML;FhirPath</PackageTags>
    <Product>Hl7.Fhir.R5.MappingLanguage</Product>
    <RootNamespace>Hl7.Fhir.MappingLanguage</RootNamespace>

    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
  </PropertyGroup>

  <PropertyGroup>
    <DefineConstants>FHIR_R5</DefineConstants>
  </PropertyGroup>
  
  <ItemGroup>
    <Compile Include="..\Hl7.Fhir.MappingLanguage\JavaExpressionNode.cs" Link="JavaExpressionNode.cs" />
    <Compile Include="..\Hl7.Fhir.MappingLanguage\JavaFhirLexer.cs" Link="JavaFhirLexer.cs" />
    <Compile Include="..\Hl7.Fhir.MappingLanguage\JavaFhirpathEngine.cs" Link="JavaFhirpathEngine.cs" />
    <Compile Include="..\Hl7.Fhir.MappingLanguage\JavaNarativeGenerator.cs" Link="JavaNarativeGenerator.cs" />
    <Compile Include="..\Hl7.Fhir.MappingLanguage\JavaProfileUtilities.cs" Link="JavaProfileUtilities.cs" />
    <Compile Include="..\Hl7.Fhir.MappingLanguage\JavaProperty.cs" Link="JavaProperty.cs" />
    <Compile Include="..\Hl7.Fhir.MappingLanguage\JavaShimExtensions.cs" Link="JavaShimExtensions.cs" />
    <Compile Include="..\Hl7.Fhir.MappingLanguage\JavaStructureMapUtils-Analyze.cs" Link="JavaStructureMapUtils-Analyze.cs" />
    <Compile Include="..\Hl7.Fhir.MappingLanguage\JavaStructureMapUtils-Execute.cs" Link="JavaStructureMapUtils-Execute.cs" />
    <Compile Include="..\Hl7.Fhir.MappingLanguage\JavaStructureMapUtils-Parse.cs" Link="JavaStructureMapUtils-Parse.cs" />
    <Compile Include="..\Hl7.Fhir.MappingLanguage\JavaTypeDetails.cs" Link="JavaTypeDetails.cs" />
    <Compile Include="..\Hl7.Fhir.MappingLanguage\JavaUtilities.cs" Link="JavaUtilities.cs" />
    <Compile Include="..\Hl7.Fhir.MappingLanguage\ValidationResult.cs" Link="ValidationResult.cs" />
		<Compile Include="..\Hl7.Fhir.MappingLanguage\LogMessage.cs" Link="LogMessage.cs" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="4.14.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
    <PackageReference Include="Hl7.Fhir.R5" Version="5.12.1" />
  </ItemGroup>

</Project>
