<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>

    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.2.3" />
    <PackageReference Include="MSTest.TestFramework" Version="4.2.3" />
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
		<PackageReference Include="Hl7.Fhir.R4B" Version="5.13.4" />
		<PackageReference Include="Hl7.Fhir.Specification.R4B" Version="5.13.4" />
		<PackageReference Include="Hl7.Fhir.Validation.Legacy.R4B" Version="5.11.0" />
		<PackageReference Include="Firely.Fhir.Packages" Version="4.9.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hl7.Fhir.MappingLanguage\Hl7.Fhir.MappingLanguage.R4B.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <None Update="TestData\observation-example.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Hl7.Fhir.Specification.Data.R4" Version="5.13.4" GeneratePathProperty="true" ExcludeAssets="all" />
		<PackageReference Include="Hl7.Fhir.Specification.Data.R4B" Version="5.13.4" GeneratePathProperty="true" ExcludeAssets="all" />
		<PackageReference Include="Hl7.Fhir.Specification.Data.R5" Version="5.13.4" GeneratePathProperty="true" ExcludeAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<!-- https://blog.dangl.me/archive/accessing-nuget-package-paths-in-your-net-sdk-based-csproj-files/ -->
		<Content Include="$(PkgHl7_Fhir_Specification_Data_R4)\contentFiles\any\any\specification.zip">
			<Link>specification.r4.zip</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<Content Include="$(PkgHl7_Fhir_Specification_Data_R4B)\contentFiles\any\any\specification.zip">
			<Link>specification.r4b.zip</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<Content Include="$(PkgHl7_Fhir_Specification_Data_R5)\contentFiles\any\any\specification.zip">
			<Link>specification.r5.zip</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<Content Include="..\specification.stu3.custom.zip" Link="specification.stu3.custom.zip">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
</Project>
